//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderData", Namespace="http://schemas.datacontract.org/2004/07/MFOrderService")]
    public partial class OrderData : object
    {
        
        private string AllRedeemField;
        
        private string BuySellField;
        
        private string BuySellTypeField;
        
        private string ClientCodeField;
        
        private string DPCField;
        
        private string DPTxnField;
        
        private string EUINField;
        
        private string EUINValField;
        
        private string EmailIDField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string Filler3Field;
        
        private string Filler4Field;
        
        private string Filler5Field;
        
        private string Filler6Field;
        
        private string FolioNoField;
        
        private string IPAddField;
        
        private string KYCStatusField;
        
        private string MandateIDField;
        
        private string MemberIdField;
        
        private string MinRedeemField;
        
        private string MobileNoField;
        
        private string OrderIdField;
        
        private string OrderValField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string Param3Field;
        
        private string PassKeyField;
        
        private string PasswordField;
        
        private string QtyField;
        
        private string RefNoField;
        
        private string RemarksField;
        
        private string SchemeCdField;
        
        private string SubBrCodeField;
        
        private string TransCodeField;
        
        private string TransNoField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllRedeem
        {
            get
            {
                return this.AllRedeemField;
            }
            set
            {
                this.AllRedeemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySell
        {
            get
            {
                return this.BuySellField;
            }
            set
            {
                this.BuySellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySellType
        {
            get
            {
                return this.BuySellTypeField;
            }
            set
            {
                this.BuySellTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPC
        {
            get
            {
                return this.DPCField;
            }
            set
            {
                this.DPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPTxn
        {
            get
            {
                return this.DPTxnField;
            }
            set
            {
                this.DPTxnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUIN
        {
            get
            {
                return this.EUINField;
            }
            set
            {
                this.EUINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUINVal
        {
            get
            {
                return this.EUINValField;
            }
            set
            {
                this.EUINValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler3
        {
            get
            {
                return this.Filler3Field;
            }
            set
            {
                this.Filler3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler4
        {
            get
            {
                return this.Filler4Field;
            }
            set
            {
                this.Filler4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler5
        {
            get
            {
                return this.Filler5Field;
            }
            set
            {
                this.Filler5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler6
        {
            get
            {
                return this.Filler6Field;
            }
            set
            {
                this.Filler6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioNo
        {
            get
            {
                return this.FolioNoField;
            }
            set
            {
                this.FolioNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdd
        {
            get
            {
                return this.IPAddField;
            }
            set
            {
                this.IPAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KYCStatus
        {
            get
            {
                return this.KYCStatusField;
            }
            set
            {
                this.KYCStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MandateID
        {
            get
            {
                return this.MandateIDField;
            }
            set
            {
                this.MandateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinRedeem
        {
            get
            {
                return this.MinRedeemField;
            }
            set
            {
                this.MinRedeemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo
        {
            get
            {
                return this.MobileNoField;
            }
            set
            {
                this.MobileNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderVal
        {
            get
            {
                return this.OrderValField;
            }
            set
            {
                this.OrderValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3
        {
            get
            {
                return this.Param3Field;
            }
            set
            {
                this.Param3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey
        {
            get
            {
                return this.PassKeyField;
            }
            set
            {
                this.PassKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemeCd
        {
            get
            {
                return this.SchemeCdField;
            }
            set
            {
                this.SchemeCdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubBrCode
        {
            get
            {
                return this.SubBrCodeField;
            }
            set
            {
                this.SubBrCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransCode
        {
            get
            {
                return this.TransCodeField;
            }
            set
            {
                this.TransCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransNo
        {
            get
            {
                return this.TransNoField;
            }
            set
            {
                this.TransNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpreadOrder", Namespace="http://schemas.datacontract.org/2004/07/MFOrderService")]
    public partial class SpreadOrder : object
    {
        
        private string AllUnitFlagField;
        
        private string BuySellField;
        
        private string BuySellTypeField;
        
        private string ClientCodeField;
        
        private string DPCField;
        
        private string DPTxnField;
        
        private string EUINField;
        
        private string EUINValField;
        
        private string EmailIDField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string Filler3Field;
        
        private string Filler4Field;
        
        private string Filler5Field;
        
        private string Filler6Field;
        
        private string FolioNoField;
        
        private string IPAddField;
        
        private string KYCStatusField;
        
        private string MemberIdField;
        
        private string MinRedeemField;
        
        private string MobileNoField;
        
        private string OrderIdField;
        
        private string OrderValField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string Param3Field;
        
        private string PassKeyField;
        
        private string PasswordField;
        
        private string RedeemDateField;
        
        private string RedemptionAmtField;
        
        private string RefNoField;
        
        private string RemarksField;
        
        private string SchemeCdField;
        
        private string SubBrCodeField;
        
        private string TransCodeField;
        
        private string TransNoField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllUnitFlag
        {
            get
            {
                return this.AllUnitFlagField;
            }
            set
            {
                this.AllUnitFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySell
        {
            get
            {
                return this.BuySellField;
            }
            set
            {
                this.BuySellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySellType
        {
            get
            {
                return this.BuySellTypeField;
            }
            set
            {
                this.BuySellTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPC
        {
            get
            {
                return this.DPCField;
            }
            set
            {
                this.DPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPTxn
        {
            get
            {
                return this.DPTxnField;
            }
            set
            {
                this.DPTxnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUIN
        {
            get
            {
                return this.EUINField;
            }
            set
            {
                this.EUINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUINVal
        {
            get
            {
                return this.EUINValField;
            }
            set
            {
                this.EUINValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler3
        {
            get
            {
                return this.Filler3Field;
            }
            set
            {
                this.Filler3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler4
        {
            get
            {
                return this.Filler4Field;
            }
            set
            {
                this.Filler4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler5
        {
            get
            {
                return this.Filler5Field;
            }
            set
            {
                this.Filler5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler6
        {
            get
            {
                return this.Filler6Field;
            }
            set
            {
                this.Filler6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioNo
        {
            get
            {
                return this.FolioNoField;
            }
            set
            {
                this.FolioNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdd
        {
            get
            {
                return this.IPAddField;
            }
            set
            {
                this.IPAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KYCStatus
        {
            get
            {
                return this.KYCStatusField;
            }
            set
            {
                this.KYCStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinRedeem
        {
            get
            {
                return this.MinRedeemField;
            }
            set
            {
                this.MinRedeemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo
        {
            get
            {
                return this.MobileNoField;
            }
            set
            {
                this.MobileNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderVal
        {
            get
            {
                return this.OrderValField;
            }
            set
            {
                this.OrderValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3
        {
            get
            {
                return this.Param3Field;
            }
            set
            {
                this.Param3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey
        {
            get
            {
                return this.PassKeyField;
            }
            set
            {
                this.PassKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedeemDate
        {
            get
            {
                return this.RedeemDateField;
            }
            set
            {
                this.RedeemDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionAmt
        {
            get
            {
                return this.RedemptionAmtField;
            }
            set
            {
                this.RedemptionAmtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemeCd
        {
            get
            {
                return this.SchemeCdField;
            }
            set
            {
                this.SchemeCdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubBrCode
        {
            get
            {
                return this.SubBrCodeField;
            }
            set
            {
                this.SubBrCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransCode
        {
            get
            {
                return this.TransCodeField;
            }
            set
            {
                this.TransCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransNo
        {
            get
            {
                return this.TransNoField;
            }
            set
            {
                this.TransNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SwitchOrder", Namespace="http://schemas.datacontract.org/2004/07/MFOrderService")]
    public partial class SwitchOrder : object
    {
        
        private string AllUnitFlagField;
        
        private string BuySellField;
        
        private string BuySellTypeField;
        
        private string ClientCodeField;
        
        private string DPTxnField;
        
        private string EUINField;
        
        private string EUINValField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string Filler3Field;
        
        private string Filler4Field;
        
        private string Filler5Field;
        
        private string Filler6Field;
        
        private string FolioNoField;
        
        private string FromSchemeCdField;
        
        private string IPAddField;
        
        private string KYCStatusField;
        
        private string MemberIdField;
        
        private string MinRedeemField;
        
        private string OrderIdField;
        
        private string OrderValField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string Param3Field;
        
        private string PassKeyField;
        
        private string PasswordField;
        
        private string RemarksField;
        
        private string SubBrCodeField;
        
        private string SwitchUnitsField;
        
        private string ToSchemeCdField;
        
        private string TransCodeField;
        
        private string TransNoField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllUnitFlag
        {
            get
            {
                return this.AllUnitFlagField;
            }
            set
            {
                this.AllUnitFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySell
        {
            get
            {
                return this.BuySellField;
            }
            set
            {
                this.BuySellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuySellType
        {
            get
            {
                return this.BuySellTypeField;
            }
            set
            {
                this.BuySellTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPTxn
        {
            get
            {
                return this.DPTxnField;
            }
            set
            {
                this.DPTxnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUIN
        {
            get
            {
                return this.EUINField;
            }
            set
            {
                this.EUINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EUINVal
        {
            get
            {
                return this.EUINValField;
            }
            set
            {
                this.EUINValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler3
        {
            get
            {
                return this.Filler3Field;
            }
            set
            {
                this.Filler3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler4
        {
            get
            {
                return this.Filler4Field;
            }
            set
            {
                this.Filler4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler5
        {
            get
            {
                return this.Filler5Field;
            }
            set
            {
                this.Filler5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler6
        {
            get
            {
                return this.Filler6Field;
            }
            set
            {
                this.Filler6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioNo
        {
            get
            {
                return this.FolioNoField;
            }
            set
            {
                this.FolioNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromSchemeCd
        {
            get
            {
                return this.FromSchemeCdField;
            }
            set
            {
                this.FromSchemeCdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdd
        {
            get
            {
                return this.IPAddField;
            }
            set
            {
                this.IPAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KYCStatus
        {
            get
            {
                return this.KYCStatusField;
            }
            set
            {
                this.KYCStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinRedeem
        {
            get
            {
                return this.MinRedeemField;
            }
            set
            {
                this.MinRedeemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderVal
        {
            get
            {
                return this.OrderValField;
            }
            set
            {
                this.OrderValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3
        {
            get
            {
                return this.Param3Field;
            }
            set
            {
                this.Param3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey
        {
            get
            {
                return this.PassKeyField;
            }
            set
            {
                this.PassKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubBrCode
        {
            get
            {
                return this.SubBrCodeField;
            }
            set
            {
                this.SubBrCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwitchUnits
        {
            get
            {
                return this.SwitchUnitsField;
            }
            set
            {
                this.SwitchUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToSchemeCd
        {
            get
            {
                return this.ToSchemeCdField;
            }
            set
            {
                this.ToSchemeCdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransCode
        {
            get
            {
                return this.TransCodeField;
            }
            set
            {
                this.TransCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransNo
        {
            get
            {
                return this.TransNoField;
            }
            set
            {
                this.TransNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SipOrder", Namespace="http://schemas.datacontract.org/2004/07/MFOrderService")]
    public partial class SipOrder : object
    {
        
        private string ClientCodeField;
        
        private string DPCField;
        
        private string DPTxnModeField;
        
        private string EuinField;
        
        private string EuinValField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string Filler3Field;
        
        private string Filler4Field;
        
        private string Filler5Field;
        
        private string Filler6Field;
        
        private string FirstOrderFlagField;
        
        private string FolioNoField;
        
        private string FrequencyAllowedField;
        
        private string FrequencyTypeField;
        
        private string IPAddField;
        
        private string InstallmentAmountField;
        
        private string InternalRefNoField;
        
        private string MemberCodeField;
        
        private string NoOfInstallmentsField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string Param3Field;
        
        private string PassKeyField;
        
        private string PasswordField;
        
        private string RegIdField;
        
        private string RemarksField;
        
        private string SchemeCodeField;
        
        private string StartDateField;
        
        private string SubberCodeField;
        
        private string TransModeField;
        
        private string TransactionCodeField;
        
        private string UniqueRefNoField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPC
        {
            get
            {
                return this.DPCField;
            }
            set
            {
                this.DPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPTxnMode
        {
            get
            {
                return this.DPTxnModeField;
            }
            set
            {
                this.DPTxnModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Euin
        {
            get
            {
                return this.EuinField;
            }
            set
            {
                this.EuinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuinVal
        {
            get
            {
                return this.EuinValField;
            }
            set
            {
                this.EuinValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler3
        {
            get
            {
                return this.Filler3Field;
            }
            set
            {
                this.Filler3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler4
        {
            get
            {
                return this.Filler4Field;
            }
            set
            {
                this.Filler4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler5
        {
            get
            {
                return this.Filler5Field;
            }
            set
            {
                this.Filler5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler6
        {
            get
            {
                return this.Filler6Field;
            }
            set
            {
                this.Filler6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstOrderFlag
        {
            get
            {
                return this.FirstOrderFlagField;
            }
            set
            {
                this.FirstOrderFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioNo
        {
            get
            {
                return this.FolioNoField;
            }
            set
            {
                this.FolioNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FrequencyAllowed
        {
            get
            {
                return this.FrequencyAllowedField;
            }
            set
            {
                this.FrequencyAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FrequencyType
        {
            get
            {
                return this.FrequencyTypeField;
            }
            set
            {
                this.FrequencyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdd
        {
            get
            {
                return this.IPAddField;
            }
            set
            {
                this.IPAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallmentAmount
        {
            get
            {
                return this.InstallmentAmountField;
            }
            set
            {
                this.InstallmentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalRefNo
        {
            get
            {
                return this.InternalRefNoField;
            }
            set
            {
                this.InternalRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberCode
        {
            get
            {
                return this.MemberCodeField;
            }
            set
            {
                this.MemberCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoOfInstallments
        {
            get
            {
                return this.NoOfInstallmentsField;
            }
            set
            {
                this.NoOfInstallmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3
        {
            get
            {
                return this.Param3Field;
            }
            set
            {
                this.Param3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey
        {
            get
            {
                return this.PassKeyField;
            }
            set
            {
                this.PassKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegId
        {
            get
            {
                return this.RegIdField;
            }
            set
            {
                this.RegIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemeCode
        {
            get
            {
                return this.SchemeCodeField;
            }
            set
            {
                this.SchemeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubberCode
        {
            get
            {
                return this.SubberCodeField;
            }
            set
            {
                this.SubberCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransMode
        {
            get
            {
                return this.TransModeField;
            }
            set
            {
                this.TransModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueRefNo
        {
            get
            {
                return this.UniqueRefNoField;
            }
            set
            {
                this.UniqueRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XsipOrder", Namespace="http://schemas.datacontract.org/2004/07/MFOrderService")]
    public partial class XsipOrder : object
    {
        
        private string BrokerageField;
        
        private string ClientCodeField;
        
        private string DPCField;
        
        private string DpTxnModeField;
        
        private string EuinField;
        
        private string EuinValField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string Filler3Field;
        
        private string Filler4Field;
        
        private string Filler5Field;
        
        private string Filler6Field;
        
        private string FirstOrderFlagField;
        
        private string FolioNoField;
        
        private string FrequencyAllowedField;
        
        private string FrequencyTypeField;
        
        private string IPAddField;
        
        private string InstallmentAmountField;
        
        private string InternalRefNoField;
        
        private string MandateIDField;
        
        private string MemberCodeField;
        
        private string NoOfInstallmentField;
        
        private string Param1Field;
        
        private string Param2Field;
        
        private string Param3Field;
        
        private string PassKeyField;
        
        private string PasswordField;
        
        private string RemarksField;
        
        private string SchemeCodeField;
        
        private string StartDateField;
        
        private string SubberCodeField;
        
        private string TransModeField;
        
        private string TransactionCodeField;
        
        private string UniqueRefNoField;
        
        private string UserIdField;
        
        private string XsipRegIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brokerage
        {
            get
            {
                return this.BrokerageField;
            }
            set
            {
                this.BrokerageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPC
        {
            get
            {
                return this.DPCField;
            }
            set
            {
                this.DPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DpTxnMode
        {
            get
            {
                return this.DpTxnModeField;
            }
            set
            {
                this.DpTxnModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Euin
        {
            get
            {
                return this.EuinField;
            }
            set
            {
                this.EuinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuinVal
        {
            get
            {
                return this.EuinValField;
            }
            set
            {
                this.EuinValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler3
        {
            get
            {
                return this.Filler3Field;
            }
            set
            {
                this.Filler3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler4
        {
            get
            {
                return this.Filler4Field;
            }
            set
            {
                this.Filler4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler5
        {
            get
            {
                return this.Filler5Field;
            }
            set
            {
                this.Filler5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler6
        {
            get
            {
                return this.Filler6Field;
            }
            set
            {
                this.Filler6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstOrderFlag
        {
            get
            {
                return this.FirstOrderFlagField;
            }
            set
            {
                this.FirstOrderFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioNo
        {
            get
            {
                return this.FolioNoField;
            }
            set
            {
                this.FolioNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FrequencyAllowed
        {
            get
            {
                return this.FrequencyAllowedField;
            }
            set
            {
                this.FrequencyAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FrequencyType
        {
            get
            {
                return this.FrequencyTypeField;
            }
            set
            {
                this.FrequencyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdd
        {
            get
            {
                return this.IPAddField;
            }
            set
            {
                this.IPAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallmentAmount
        {
            get
            {
                return this.InstallmentAmountField;
            }
            set
            {
                this.InstallmentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalRefNo
        {
            get
            {
                return this.InternalRefNoField;
            }
            set
            {
                this.InternalRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MandateID
        {
            get
            {
                return this.MandateIDField;
            }
            set
            {
                this.MandateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberCode
        {
            get
            {
                return this.MemberCodeField;
            }
            set
            {
                this.MemberCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoOfInstallment
        {
            get
            {
                return this.NoOfInstallmentField;
            }
            set
            {
                this.NoOfInstallmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param1
        {
            get
            {
                return this.Param1Field;
            }
            set
            {
                this.Param1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param2
        {
            get
            {
                return this.Param2Field;
            }
            set
            {
                this.Param2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Param3
        {
            get
            {
                return this.Param3Field;
            }
            set
            {
                this.Param3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey
        {
            get
            {
                return this.PassKeyField;
            }
            set
            {
                this.PassKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemeCode
        {
            get
            {
                return this.SchemeCodeField;
            }
            set
            {
                this.SchemeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubberCode
        {
            get
            {
                return this.SubberCodeField;
            }
            set
            {
                this.SubberCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransMode
        {
            get
            {
                return this.TransModeField;
            }
            set
            {
                this.TransModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueRefNo
        {
            get
            {
                return this.UniqueRefNoField;
            }
            set
            {
                this.UniqueRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XsipRegID
        {
            get
            {
                return this.XsipRegIDField;
            }
            set
            {
                this.XsipRegIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bsestarmf.in/", ConfigurationName="MFServices.MFOrderEntry")]
    public interface MFOrderEntry
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/getPassword", ReplyAction="http://bsestarmf.in/MFOrderEntry/getPasswordResponse")]
        System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/OrderEntry", ReplyAction="http://bsestarmf.in/MFOrderEntry/OrderEntryResponse")]
        System.Threading.Tasks.Task<string> OrderEntryAsync(MFServices.OrderData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/orderEntryParam", ReplyAction="http://bsestarmf.in/MFOrderEntry/orderEntryParamResponse")]
        System.Threading.Tasks.Task<string> orderEntryParamAsync(
                    string TransCode, 
                    string TransNo, 
                    string OrderId, 
                    string UserID, 
                    string MemberId, 
                    string ClientCode, 
                    string SchemeCd, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderVal, 
                    string Qty, 
                    string AllRedeem, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string RefNo, 
                    string SubBrCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string DPC, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Parma1, 
                    string Param2, 
                    string Param3, 
                    string MobileNo, 
                    string EmailID, 
                    string MandateID, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntry", ReplyAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryResponse")]
        System.Threading.Tasks.Task<string> spreadOrderEntryAsync(MFServices.SpreadOrder data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParam", ReplyAction="http://bsestarmf.in/MFOrderEntry/spreadOrderEntryParamResponse")]
        System.Threading.Tasks.Task<string> spreadOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string OrderID, 
                    string UserID, 
                    string MemberId, 
                    string ClientCode, 
                    string SchemeCode, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderValue, 
                    string RedemptionAmt, 
                    string AllUnitFlag, 
                    string RedeemDate, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string RefNo, 
                    string SubBroCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string DPC, 
                    string IPAddress, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string MobileNo, 
                    string EmailID, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntry", ReplyAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntryResponse")]
        System.Threading.Tasks.Task<string> switchOrderEntryAsync(MFServices.SwitchOrder data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParam", ReplyAction="http://bsestarmf.in/MFOrderEntry/switchOrderEntryParamResponse")]
        System.Threading.Tasks.Task<string> switchOrderEntryParamAsync(
                    string TransCode, 
                    string TransNo, 
                    string OrderId, 
                    string UserId, 
                    string MemberId, 
                    string ClientCode, 
                    string FromSchemeCd, 
                    string ToSchemeCd, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderVal, 
                    string SwitchUnits, 
                    string AllUnitsFlag, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string SubBrCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Parma1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntry", ReplyAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntryResponse")]
        System.Threading.Tasks.Task<string> sipOrderEntryAsync(MFServices.SipOrder data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParam", ReplyAction="http://bsestarmf.in/MFOrderEntry/sipOrderEntryParamResponse")]
        System.Threading.Tasks.Task<string> sipOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string SchemeCode, 
                    string MemberCode, 
                    string ClientCode, 
                    string UserID, 
                    string InternalRefNo, 
                    string TransMode, 
                    string DpTxnMode, 
                    string StartDate, 
                    string FrequencyType, 
                    string FrequencyAllowed, 
                    string InstallmentAmount, 
                    string NoOfInstallment, 
                    string Remarks, 
                    string FolioNo, 
                    string FirstOrderFlag, 
                    string SubberCode, 
                    string Euin, 
                    string EuinVal, 
                    string DPC, 
                    string RegId, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntry", ReplyAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryResponse")]
        System.Threading.Tasks.Task<string> xsipOrderEntryAsync(MFServices.XsipOrder data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParam", ReplyAction="http://bsestarmf.in/MFOrderEntry/xsipOrderEntryParamResponse")]
        System.Threading.Tasks.Task<string> xsipOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string SchemeCode, 
                    string MemberCode, 
                    string ClientCode, 
                    string UserId, 
                    string InternalRefNo, 
                    string TransMode, 
                    string DpTxnMode, 
                    string StartDate, 
                    string FrequencyType, 
                    string FrequencyAllowed, 
                    string InstallmentAmount, 
                    string NoOfInstallment, 
                    string Remarks, 
                    string FolioNo, 
                    string FirstOrderFlag, 
                    string Brokerage, 
                    string MandateID, 
                    string SubberCode, 
                    string Euin, 
                    string EuinVal, 
                    string DPC, 
                    string XsipRegID, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MFOrderEntryChannel : MFServices.MFOrderEntry, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MFOrderEntryClient : System.ServiceModel.ClientBase<MFServices.MFOrderEntry>, MFServices.MFOrderEntry
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MFOrderEntryClient(EndpointConfiguration endpointConfiguration) : 
                base(MFOrderEntryClient.GetBindingForEndpoint(endpointConfiguration), MFOrderEntryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFOrderEntryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MFOrderEntryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFOrderEntryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MFOrderEntryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MFOrderEntryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string Password, string PassKey)
        {
            return base.Channel.getPasswordAsync(UserId, Password, PassKey);
        }
        
        public System.Threading.Tasks.Task<string> OrderEntryAsync(MFServices.OrderData data)
        {
            return base.Channel.OrderEntryAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> orderEntryParamAsync(
                    string TransCode, 
                    string TransNo, 
                    string OrderId, 
                    string UserID, 
                    string MemberId, 
                    string ClientCode, 
                    string SchemeCd, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderVal, 
                    string Qty, 
                    string AllRedeem, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string RefNo, 
                    string SubBrCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string DPC, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Parma1, 
                    string Param2, 
                    string Param3, 
                    string MobileNo, 
                    string EmailID, 
                    string MandateID, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6)
        {
            return base.Channel.orderEntryParamAsync(TransCode, TransNo, OrderId, UserID, MemberId, ClientCode, SchemeCd, BuySell, BuySellType, DPTxn, OrderVal, Qty, AllRedeem, FolioNo, Remarks, KYCStatus, RefNo, SubBrCode, EUIN, EUINVal, MinRedeem, DPC, IPAdd, Password, PassKey, Parma1, Param2, Param3, MobileNo, EmailID, MandateID, Filler1, Filler2, Filler3, Filler4, Filler5, Filler6);
        }
        
        public System.Threading.Tasks.Task<string> spreadOrderEntryAsync(MFServices.SpreadOrder data)
        {
            return base.Channel.spreadOrderEntryAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> spreadOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string OrderID, 
                    string UserID, 
                    string MemberId, 
                    string ClientCode, 
                    string SchemeCode, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderValue, 
                    string RedemptionAmt, 
                    string AllUnitFlag, 
                    string RedeemDate, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string RefNo, 
                    string SubBroCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string DPC, 
                    string IPAddress, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string MobileNo, 
                    string EmailID, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6)
        {
            return base.Channel.spreadOrderEntryParamAsync(TransactionCode, UniqueRefNo, OrderID, UserID, MemberId, ClientCode, SchemeCode, BuySell, BuySellType, DPTxn, OrderValue, RedemptionAmt, AllUnitFlag, RedeemDate, FolioNo, Remarks, KYCStatus, RefNo, SubBroCode, EUIN, EUINVal, MinRedeem, DPC, IPAddress, Password, PassKey, Param1, Param2, Param3, MobileNo, EmailID, Filler1, Filler2, Filler3, Filler4, Filler5, Filler6);
        }
        
        public System.Threading.Tasks.Task<string> switchOrderEntryAsync(MFServices.SwitchOrder data)
        {
            return base.Channel.switchOrderEntryAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> switchOrderEntryParamAsync(
                    string TransCode, 
                    string TransNo, 
                    string OrderId, 
                    string UserId, 
                    string MemberId, 
                    string ClientCode, 
                    string FromSchemeCd, 
                    string ToSchemeCd, 
                    string BuySell, 
                    string BuySellType, 
                    string DPTxn, 
                    string OrderVal, 
                    string SwitchUnits, 
                    string AllUnitsFlag, 
                    string FolioNo, 
                    string Remarks, 
                    string KYCStatus, 
                    string SubBrCode, 
                    string EUIN, 
                    string EUINVal, 
                    string MinRedeem, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Parma1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6)
        {
            return base.Channel.switchOrderEntryParamAsync(TransCode, TransNo, OrderId, UserId, MemberId, ClientCode, FromSchemeCd, ToSchemeCd, BuySell, BuySellType, DPTxn, OrderVal, SwitchUnits, AllUnitsFlag, FolioNo, Remarks, KYCStatus, SubBrCode, EUIN, EUINVal, MinRedeem, IPAdd, Password, PassKey, Parma1, Param2, Param3, Filler1, Filler2, Filler3, Filler4, Filler5, Filler6);
        }
        
        public System.Threading.Tasks.Task<string> sipOrderEntryAsync(MFServices.SipOrder data)
        {
            return base.Channel.sipOrderEntryAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> sipOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string SchemeCode, 
                    string MemberCode, 
                    string ClientCode, 
                    string UserID, 
                    string InternalRefNo, 
                    string TransMode, 
                    string DpTxnMode, 
                    string StartDate, 
                    string FrequencyType, 
                    string FrequencyAllowed, 
                    string InstallmentAmount, 
                    string NoOfInstallment, 
                    string Remarks, 
                    string FolioNo, 
                    string FirstOrderFlag, 
                    string SubberCode, 
                    string Euin, 
                    string EuinVal, 
                    string DPC, 
                    string RegId, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6)
        {
            return base.Channel.sipOrderEntryParamAsync(TransactionCode, UniqueRefNo, SchemeCode, MemberCode, ClientCode, UserID, InternalRefNo, TransMode, DpTxnMode, StartDate, FrequencyType, FrequencyAllowed, InstallmentAmount, NoOfInstallment, Remarks, FolioNo, FirstOrderFlag, SubberCode, Euin, EuinVal, DPC, RegId, IPAdd, Password, PassKey, Param1, Param2, Param3, Filler1, Filler2, Filler3, Filler4, Filler5, Filler6);
        }
        
        public System.Threading.Tasks.Task<string> xsipOrderEntryAsync(MFServices.XsipOrder data)
        {
            return base.Channel.xsipOrderEntryAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> xsipOrderEntryParamAsync(
                    string TransactionCode, 
                    string UniqueRefNo, 
                    string SchemeCode, 
                    string MemberCode, 
                    string ClientCode, 
                    string UserId, 
                    string InternalRefNo, 
                    string TransMode, 
                    string DpTxnMode, 
                    string StartDate, 
                    string FrequencyType, 
                    string FrequencyAllowed, 
                    string InstallmentAmount, 
                    string NoOfInstallment, 
                    string Remarks, 
                    string FolioNo, 
                    string FirstOrderFlag, 
                    string Brokerage, 
                    string MandateID, 
                    string SubberCode, 
                    string Euin, 
                    string EuinVal, 
                    string DPC, 
                    string XsipRegID, 
                    string IPAdd, 
                    string Password, 
                    string PassKey, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Filler1, 
                    string Filler2, 
                    string Filler3, 
                    string Filler4, 
                    string Filler5, 
                    string Filler6)
        {
            return base.Channel.xsipOrderEntryParamAsync(TransactionCode, UniqueRefNo, SchemeCode, MemberCode, ClientCode, UserId, InternalRefNo, TransMode, DpTxnMode, StartDate, FrequencyType, FrequencyAllowed, InstallmentAmount, NoOfInstallment, Remarks, FolioNo, FirstOrderFlag, Brokerage, MandateID, SubberCode, Euin, EuinVal, DPC, XsipRegID, IPAdd, Password, PassKey, Param1, Param2, Param3, Filler1, Filler2, Filler3, Filler4, Filler5, Filler6);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_MFOrderEntry))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_MFOrderEntry1))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_MFOrderEntry))
            {
                return new System.ServiceModel.EndpointAddress("http://pbustarmfsrv113.bseltd.domain/MFOrderEntry/MFOrder.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_MFOrderEntry1))
            {
                return new System.ServiceModel.EndpointAddress("https://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc/Secure");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_MFOrderEntry,
            
            WSHttpBinding_MFOrderEntry1,
        }
    }
}
